### ISSUE TITLE
network upgrade role

### ISSUE THREAD

**Issue by IPvSean** [ansible-network/network-proposals#4]
# Proposal: network_upgrade role

*Author*: Sean Cavanaugh <@IPvSean> 

*Date*: 2018-11-08

- Status: New
- Proposal type: role
- Targeted release: new
- Associated PR: none
- Estimated time to implement: unknown... might take procurement of some hardware

## Motivation

This proposal describes the implementation of a new network function role for an agnostic approach for performing device upgrades.  

### Problems
What problems exist that this proposal will solve?
- Upgrades are a normal routine tasks that network operators have to perform, and many of them are creating playbooks (or even have specific modules like [Lenovo cnos](https://docs.ansible.com/ansible/latest/modules/cnos_image_module.html#cnos-image-module)).  Having a standard role will make this easier for network operators to use on day 1
- Dealing with a reboot is difficult (when device looses connectivity) and providing a clear role on how to do this on platforms will be ideal
- Most multi-vendor environments will be forced to make roles regardless because the way upgrades behave between vendors can be quite different.  Creating something like this is inevitable for a network operator wanting to use ansible.

## Solution proposal
- Some SAs have created Playbooks for upgrades, e.g. https://github.com/colin-mccarthy/ansible_upgrade e.g. @colin-mccarthy 

- Describe your suggested solution here.
- Insert code in snippets if you would like as shown.
```yaml
---
- hosts: network
  connection: network_cli
  gather_facts: false


  roles:
    - name: ansible-network.network_upgrade
      function: upgrade
      network_upgrade_image: c2600-adventerprisek9-mz.124-15.T14.bin
      network_upgrade_reboot: True
```
- Be sure to explain how this solves problems.

Trying to copy format of config_manager role.  We can make network_upgrade_reboot a flag so we only reboot if we want it to, otherwise it just installs upgrade and depending on OS it won't roll over until its rebooted (sometimes organizations will update, then reboot during change window).

## Dependencies (optional)
Explain any dependencies. This section is optional but could be helpful.
- provider roles for Cisco IOS, NX-OS, IOS-XR, Arista EOS and Juniper JunOS.
- most likely net_put?

## Testing (optional)
Does / should this require testing, and if so, how? Describe here. This section is optional but could be helpful.

Yes, this should require testing and be part of our Zuul integration with vendors since it requires a reboot.

## Documentation (optional)
Does / should this require documentation? If so, describe here. This section is optional but could be helpful.

Yes this network function role should be how customers adopt Playbooks.  This is a common and routine tasks for network operators, and ideally this would be easy to use within Tower (select devices, select images, upgrade).

## Anything else?
If you'd like to add anything else beyond the above required and optional sections, you are welcome to do so.

Probably want to create a backup similarly to the config_manager role, or somehow use the config_manager role to get the backup before we attempt an upgrade and rollback if somehow something fails.

**Comment by cidrblock** [comment]
This is a good candidate for the network collection, tracking elsewhere.
