### ISSUE TITLE
Create asa_facts module

### ISSUE THREAD

**Issue by colin-mccarthy** [ansible-network/network-proposals#6]
# Proposal: <Create asa_facts module>

*Author*: Colin Mccarthy <@colin-mccarthy> 

*Date*: 2019-02-13

- Status: New
- Proposal type: (module)
- Targeted release: <unknown>
- Associated PR: <none>
- Estimated time to implement: <unknown>

## Motivation
Describe the reasons for this proposal.

Customers enjoy using the` _facts` modules but then are disapointed to learn one does not exist for asa.

### Problems
What problems exist that this proposal will solve?

Playbooks that are written for ios or nxos and use _facts modules have to be completely re worked when wanting to run those types of tasks on ASA. This becomes a blocker for some folks who can't easily write parsers.

**Comment by NilashishC** [comment]
@colin-mccarthy Could you please open a feature request under ansible/ansible for this new module?

**Comment by colin-mccarthy** [comment]
Sure! I will do that, Thanks

**Comment by gundalow** [comment]
as per above, closing
